apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "railgun_relayer.fullname" . }}-relayer
  labels:
{{ include "railgun_relayer.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "railgun_relayer.name" . }}-relayer
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "railgun_relayer.name" . }}-relayer
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.railgun_relayer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      serviceAccountName: {{ template "railgun_relayer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.railgun_relayer.image.repository }}:{{ tpl .Values.railgun_relayer.image.tag . }}"
          imagePullPolicy: {{ .Values.railgun_relayer.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "railgun_relayer.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: initdb
          emptyDir: {}
