apiVersion: v1
kind: Secret
metadata:
  name: {{ include "railgun-relayer.fullname" . }}
  labels:
{{ include "railgun-relayer.labels" . | indent 4 }}
type: Opaque
stringData:
  WAKU_RPC_URL: 'http://railgun-relayer-nwaku:8546'
  LEPTON_DB: '/mnt/relayer.db'
  LOG_LEVEL: 'debug'
  DEBUG: 'relayer*,waku:jsonrpc-api'
  {{- range $key, $value := index .Values "railgun-relayer.settings" }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
