{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "railgun_relayer.serviceAccountName" . }}
  labels:
{{ include "railgun_relayer.labels" . | indent 4 }}
{{- end -}}
