{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "railgun-relayer.serviceAccountName" . }}
  labels:
{{ include "railgun-relayer.labels" . | indent 4 }}
{{- end -}}
