apiVersion: v1
kind: Service
metadata:
  name: {{ include "railgun-relayer.fullname" . }}-nwaku
  labels:
{{ include "railgun-relayer.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 60000
      targetPort: waku-a
      protocol: TCP
      name: waku-a
    - port: 8000
      targetPort: waku-b
      protocol: TCP
      name: waku-b
    - port: 8546
      targetPort: waku-c
      protocol: TCP
      name: waku-c

  selector:
    app.kubernetes.io/name: {{ include "railgun-relayer.name" . }}-nwaku
    app.kubernetes.io/instance: {{ .Release.Name }}
