apiVersion: v1
kind: Service
metadata:
  name: {{ include "railgun_relayer.fullname" . }}-nwaku
  labels:
{{ include "railgun_relayer.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 60000
      targetPort: wakuA
      protocol: TCP
      name: wakuA
    - port: 8000
      targetPort: wakuB
      protocol: TCP
      name: wakuB
  selector:
    app.kubernetes.io/name: {{ include "railgun_relayer.name" . }}-nwaku
    app.kubernetes.io/instance: {{ .Release.Name }}
